name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: mikeparcewski/wicked-ci/.github/workflows/node-ci.yml@d8c9b0a14fb91c2d13f5da0468eeeff983c27e5a # v1.1.2
    with:
      test_cmd: 'npm test && npm run test:unit'
