name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: mikeparcewski/wicked-ci/.github/workflows/node-ci.yml@0382b46d00d772c09911f9d00021e0172eb9abe4 # v1.1.0
